# Generated by Django 5.0.1 on 2024-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_info_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='banner',
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
