# Generated by Django 5.0.1 on 2024-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sertificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default=1, upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.CharField(max_length=600),
        ),
    ]
